src/CMS/BlogBundle/Entity/Image.php
<?php

namespace CMS\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="CMS\BlogBundle\Repository\ImageRepository")
 *
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255, nullable=true)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;


    /**
     * @var UploadedFile
     */
    private $file;

    // on ajoute une mémoire tampon
    private $tempFilename;

    /**
     * @var string
     * @ORM\Column(name="url_enligne", type="string", length=255, nullable=true)
     */
    private $url_enligne;

    /**
     * @var string
     * @ORM\Column(name="alt_enligne", type="string", length=255, nullable=true)
     */
    private $alt_enligne;

    /**
     * @param UploadedFile $file
     */
    public function setFile(UploadedFile $file)
    {
        $this->file = $file;

        // Vérification si on a déjà un fichier pour cette entité
        if ($this->url !== null) {
            $this->tempFilename = $this->url;

            // Réinitialisation des ttribut url et alt
            $this->url = null;
            $this->alt = null;
        }
    }


    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {

        // si il n'y a pas de fichier on fait rien
        if ($this->file === null) {
            return;
        }

        // le nom du fichier est son id, on doit juste stocker son extensino
        $this->url = $this->file->guessExtension();

        // on attriut a alt, la valeur du nom de fichier sur le pc de l'util
        $this->alt = $this->file->getClientOriginalName();
    }


    /**
     * Début fonction upload
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {

        // si pas de fichier on ne fait rien
        if (null === $this->file) {
            return;
        }

        // Si on a un ancien fichier on le supprime
        if ($this->tempFilename !== null) {
            $oldFile = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->tempFilename;
            if (file_exists($oldFile)) {
                unlink($oldFile);
            }
        }

        // On déplace le fichier envoyé dans le répertoire de notre choxi
        $this->file->move(
            $this->getUploadRootDir(),
            $this->id . '.' . $this->url
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir() . '/' . $this->id . '.' . $this->url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
        if (file_exists($this->tempFilename)) {
            // On supprime le fichier
            unlink($this->tempFilename);
        }
    }

    /**
     * Retourne le chemin relatif
     */
    public function getUploadDir()
    {
        return 'uploads/img';
    }

    /**
     * Retourne le chemin relatif vers l'image pour notre code php
     */
    public function getUploadRootDir()
    {
        return __DIR__ . '/../../../../web/' . $this->getUploadDir();
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getFile()
    {
        return $this->file;
    }



    /**
     * Set urlEnligne
     *
     * @param string $urlEnligne
     *
     * @return Image
     */
    public function setUrlEnligne($urlEnligne)
    {
        $this->url_enligne = $urlEnligne;

        return $this;
    }

    /**
     * Get urlEnligne
     *
     * @return string
     */
    public function getUrlEnligne()
    {
        return $this->url_enligne;
    }

    /**
     * Set altEnligne
     *
     * @param string $altEnligne
     *
     * @return Image
     */
    public function setAltEnligne($altEnligne)
    {
        $this->alt_enligne = $altEnligne;

        return $this;
    }

    /**
     * Get altEnligne
     *
     * @return string
     */
    public function getAltEnligne()
    {
        return $this->alt_enligne;
    }
}

src/CMS/BlogBundle/Form/CarouselType.php
<?php

namespace CMS\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarouselType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('published', CheckboxType::class, array(
                'label'=>'Cochez pour publier',
                'required' => false
            ))
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\BlogBundle\Entity\Carousel'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'cms_blogbundle_carousel';
    }


}

src/CMS/BlogBundle/Controller/CarouselController.php
<?php

namespace CMS\BlogBundle\Controller;

use CMS\BlogBundle\Entity\Carousel;
use CMS\BlogBundle\Entity\Gallery;
use CMS\BlogBundle\Form\CarouselType;
use CMS\BlogBundle\Form\GalleryType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/*Utilisé en annotation*/
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;


class CarouselController extends Controller
{

    /**
     * To display main page with published carousel existant
     *
     * @return \Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        $carousel = $em->getRepository('CMSBlogBundle:Carousel')->findAll();

        $gallery = $em
            ->getRepository('CMSBlogBundle:Gallery')
            ->findAll();

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:index.html.twig',
            [
                'carousel' => $carousel,
                'gallery' => $gallery,
                'custom' => $custom
            ]
        );
    }

    /**
     * Add Carousel name and is published
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function addAction(Request $request)
    {

        // Initializing Entity Manager
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // Création d'une nouvelle entité article
        $carousel = new Carousel();

        $form = $this->get('form.factory')->create(CarouselType::class, $carousel);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($carousel);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Carousel enregistré.');

            return $this->redirectToRoute(
                'cms_custom_carousel'
            );
        }

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:add.html.twig',
            [
                'form' => $form->createView(),
                'custom' => $custom
            ]
        );
    }

    /**
     * Add gallery photo to an existant carousel
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function addGalleryAction(Request $request)
    {

        // Initializing Entity Manager
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // Création d'une nouvelle entité article
        $gallery = new Gallery();

        $form = $this->get('form.factory')->create(GalleryType::class, $gallery);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($gallery);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Image enregistrée.');

            return $this->redirectToRoute(
                'cms_custom_carousel'
            );
        }

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:add.html.twig',
            [
                'form' => $form->createView(),
                'custom' => $custom
            ]
        );

    }

    /**
     * To edit the selectionned Carousel
     *
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function editCarouselAction($id, Request $request)
    {

        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // o recup l'annonce en question
        $carousel = $em->getRepository('CMSBlogBundle:Carousel')->find($id);

        if ($carousel === null) {
            throw new NotFoundHttpException("Le carousel " . $id . " n'existe pas.");
        }

        $form = $this->get('form.factory')->create(CarouselType::class, $carousel);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {

            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Carousel bien modifié.');

            return $this->redirectToRoute(
                'cms_custom_carousel'
            );
        }

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:edit.html.twig',
            [
                'carousel' => $carousel,
                'form' => $form->createView(),
                'custom' => $custom
            ]
        );
    }

    /**
     * To delete a carousel
     *
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteCarouselAction($id, Request $request)
    {

        // Initializing Entity Manager
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // On récupérère l'article par son id
        $carousel = $em->getRepository('CMSBlogBundle:Carousel')->find($id);

        if ($carousel === null) {
            throw new NotFoundHttpException("Le carousel : " . $id . " n'existe pas .");
        }

        // On crée un formulaire vide, qui ne contiendra que le champ CSRF
        // Cela permet de protéger la suppression d'annonce contre cette faille
        $form = $this->get('form.factory')->create();

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em->remove($carousel);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info', "Le carousel a bien été supprimé.");

            return $this->redirectToRoute('cms_custom_carousel');
        }

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:delete.html.twig',
            [
                'carousel' => $carousel,
                'form' => $form->createView(),
                'custom' => $custom
            ]
        );
    }


    /**
     * To display carousel on index page
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     *
     */
    public function isPublishedAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        // To display the carousel
        $carousel = $em->getRepository('CMSBlogBundle:Carousel')->findBy(
            array('published' => true),
            array()
        );

        $gallery = $em->getRepository('CMSBlogBundle:Gallery')->findAll();

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:show.html.twig',
            [
                'carousel' => $carousel,
                'gallery' => $gallery
            ]
        );

    }

    /**
     * To display carousel on Test/brouillon page
     *
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function isNoPublishedTestAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // To display the carousel
        $carousel = $em->getRepository('CMSBlogBundle:Carousel')->findBy(
            array('published' => false),
            array()
        );

        $gallery = $em->getRepository('CMSBlogBundle:Gallery')->findAll();

        return $this->render(
            'CMSBlogBundle:Custom/Carousel:showTest.html.twig',
            [
                'carousel' => $carousel,
                'gallery' => $gallery,
                'custom' => $custom
            ]
        );
    }

    /**
     * To delete an image on the carousel
     *
     * @param $id
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     *
     * @Security("has_role('ROLE_ADMIN')")
     */
    public function deleteGalleryAction($id, Request $request)
    {
        // Initializing Entity Manager
        $em = $this->getDoctrine()->getManager();

        // Pour le theme
        $custom = $em->getRepository('CMSBlogBundle:Custom')->findAll();

        // On récupérère l'article par son id
        $gallery = $em->getRepository('CMSBlogBundle:Gallery')->find($id);

        if ($gallery === null) {
            throw new NotFoundHttpException("L'image d'id : " . $id . " n'existe pas .");
        }

        // On crée un formulaire vide, qui ne contiendra que le champ CSRF
        // Cela permet de protéger la suppression d'annonce contre cette faille
        $form = $this->get('form.factory')->create();

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $em->remove($gallery);
            $em->flush();

            $request->getSession()->getFlashBag()->add('info', "L'image a bien été supprimée.");

            return $this->redirectToRoute('cms_custom_carousel');
        }

        return $this->render(
            'CMSBlogBundle:Custom/Gallery:delete.html.twig',
            [

src/CMS/BlogBundle/Resources/views/Custom/Carousel/add.html.twig
{% extends "CMSBlogBundle::layout.html.twig" %}

{% block title %}
    Création d'un carousel - {{ parent() }}
{% endblock %}

{% block cms_body %}

    <h2>Configuration du carousel</h2>

    <div class="row">
        <div class="flip">
            <h3>
                <button class="btn btn-info pull-right btn-sm" style="margin-right: 2em;"><i class="fa fa-info" aria-hidden="true"></i>&nbsp;&nbsp;Aide</button>
            </h3>
        </div>

        <div class="panel-flip">
            <ul class="bg-info">
                <li>Dans un premier temps, attribuer un nom (aucune importance) au carousel</li>
                <li>Vous allez pouvoir uploader 3 images</li>
                <li>Les attribuer au carousel préalablement créé</li>
                <li>Ajouter une description qui apparaitra dans le footer du carousel</li>
            </ul>
        </div>

    </div>

    <br>

    {{ include("CMSBlogBundle:Custom/Carousel:form.html.twig") }}

{% endblock %}

src/CMS/BlogBundle/Resources/views/Custom/Carousel/delete.html.twig
{% extends "CMSBlogBundle::layout.html.twig" %}

{% block title %}
    Supprimer le carousel - {{ parent() }}
{% endblock %}

{% block cms_body %}

    <h2>Supprimer le carousel</h2>

    <p class="alert alert-warning">
        Etes-vous certain de vouloir supprimer le carousel "{{ carousel.nom }}" ?
    </p>

    <form action="{{ path('cms_custom_carousel_delete', {'id': carousel.id}) }}" method="post">
        <a href="{{ path('cms_custom_carousel') }}" class="btn btn-success btn-sm">
            <i class="glyphicon glyphicon-chevron-left"></i>
            Retour aux paramètres
        </a>
        {# Ici j'ai écrit le bouton de soumission à la main #}
        <button type="submit" class="btn btn-danger btn-sm"><i class="fa fa-trash-o" aria-hidden="true"></i>&nbsp;&nbsp;Supprimer
        </button>
        {# Ceci va générer le champ CSRF #}
        {{ form_rest(form) }}
    </form>

{% endblock %}

src/CMS/BlogBundle/Resources/views/Custom/Carousel/index.html.twig
{% extends 'CMSBlogBundle::layout.html.twig' %}

{% block title %}
    Gestion d'un carousel - {{ parent() }}
{% endblock %}

{% block cms_body %}
    <h2>Gestion d'un carousel</h2>
    {% set newArray = [] %}
    <div class="row">

        {% include('CMSCoreBundle:Core:flashbag.html.twig') %}

            <div class="flip">
                <h3>
                    <button class="btn btn-info btn-xs pull-right" style="margin-right: 2em;"><i class="fa fa-info" aria-hidden="true"></i>&nbsp;&nbsp;Aide
                    </button>
                </h3>

        <div class="panel-flip bg-info">
            <ul>
                <li>Ici vous pouvez créer un carousel</li>
                <li>Dans un premier temps lui attribuer un nom</li>
                <li>Dans un second temps lui attribuer des photos (trois au maximum)</li>
                <li>Et pour finir le publier ou non et voir son brouillon...</li>
                <li>Bientot possibilité sera faite de créer plusieurs carousels</li>
            </ul>
        </div>
        </div>
    </div>
    <div class="row">

        {% if carousel is empty or carousel is null %}
            <div class="col-md-6 col-xs-6">
                <a href="{{ path('cms_custom_carousel_add') }}">Ajouter un Carousel &nbsp;&nbsp;<i
                            class="fa fa-arrow-circle-o-right" aria-hidden="true"></i></a><br>
            </div>
        {% else %}
            <div class="col-md-6 col-xs-6">
                <a title="Supprimer l'existant pour en créer un autre" class="pointer">Ajouter un Carousel</a>
            </div>

            {#{% for key, galleries in gallery %}#}
            {% if gallery|length not in newArray %} {# je calcule la longueur de mon tableau et je groupe#}
                {% set newArray = newArray|merge([gallery|length]) %}
                {% if gallery|length <3 %}
                    <div class="col-md-6 col-xs-6">
                        <a href="{{ path('cms_custom_carousel_add_gallery') }}">Ajouter des photos&nbsp;&nbsp;<i
                                    class="fa fa-arrow-circle-o-right" aria-hidden="true"></i></a>
                    </div>
                {% else %}
                    <div class="col-md-6 col-xs-6">
                        <a title="Vous ne pouvez mettre que 3 photos !" class="pointer">Ajouter des photos</a>
                    </div>
                {% endif %}
            {% endif %}
            {#{% endfor %}#}

            <div class="col-md-6 col-xs-6">
                <a href="{{ path('cms_custom_carousel_show_test') }}">Test Slider&nbsp;&nbsp;<i
                            class="fa fa-arrow-circle-o-right" aria-hidden="true"></i></a>
            </div>

        {% endif %}

    </div>

    {% for key, carousels in carousel %}
        {% if carousels %}
            <div class="row">
            <h3>Carousel existant</h3>
            {% for key, carousels in carousel %}
                {% if carousels.nom is not empty %}
                    {% set newArray = newArray|merge([carousels.nom]) %}
                    <h4>Nom du carousel : {{ carousels.nom|capitalize }}</h4>
                {% endif %}
            {% endfor %}

            {% for key, galleries in gallery %}
                <div class="col-md-3 col-xs-4">
                    <div class="thumbnail">
                        {% if galleries.carousel.id == carousels.id %}

                            <img src="{{ asset(galleries.uploadDir ~ '/' ~ galleries.id ~ '.' ~ galleries.url) }}"
                                 alt="{{ galleries.alt }}"/>

                            <div class="caption">
                                <p>
                                    <a href="{{ path('cms_custom_carousel_edit_gallery', {'id': galleries.id}) }}"
                                       class="btn btn-warning btn-xs" role="button"><i
                                                class="glyphicon glyphicon-edit"></i></a>
                                    <a href="{{ path('cms_custom_carousel_delete_gallery', {'id': galleries.id}) }}"
                                       class="btn btn-danger btn-xs" role="button"><i
                                                class="glyphicon glyphicon-trash"></i></a>
                                </p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}

        {% endif %}
        </div>
        <div class="row">
            <p>
                {% if is_granted('ROLE_AUTEUR') %}
                    <a href="{{ path('cms_custom_index') }}" class="btn btn-success btn-sm">
                        <i class="glyphicon glyphicon-edit"></i>
                        Retour à la page précédente
                    </a>
                    {% if carousels.id not in newArray %}
                        {% set newArray = newArray|merge([carousels.id]) %}
                        <a href="{{ path('cms_custom_carousel_edit', { 'id': carousels.id } ) }}"
                           class="btn btn-warning btn-sm">
                            <i class="glyphicon glyphicon-edit"></i>
                            Modifier le carousel
                        </a>
                        <a href="{{ path('cms_custom_carousel_delete', { 'id': carousels.id }) }}"
                           class="btn btn-danger btn-sm">
                            <i class="glyphicon glyphicon-trash"></i>
                            Supprimer le carousel
                        </a>
                    {% endif %}
                {% endif %}
            </p>
        </div>

    {% endfor %}
{% endblock %}

src/CMS/BlogBundle/Resources/views/Custom/Carousel/show.html.twig
{% block stylesheets %}
    <style>
        .carousel .item {
            max-height: 300px;
            min-height: 300px
        }

        .carousel img {
            position: absolute;
            top: 0;
            left: 0;
            min-width: 100%;
            height: 500px;
        }

        #myCarousel > div {
            background-color: black;
        }

    </style>
{% endblock %}

{% block cms_body %}
    {% if carousel %}
        <div class="bs-example">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Carousel indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- Wrapper for carousel items -->
                <div class="carousel-inner">
                    {% for img in gallery %}
                        {% if loop.index == 1 %}
                            <div class="item active">
                                <img src="{{ asset(img.uploadDir ~ '/' ~ img.id ~ '.' ~ img.url) }}"
                                     alt="{{ img.alt }}"/>
                                <div class="carousel-caption">
                                    {% if img.description is not null %}
                                        <i class="fa fa-quote-left"
                                           aria-hidden="true"></i>&nbsp;&nbsp; {{ img.description }}&nbsp;&nbsp;<i
                                            class="fa fa-quote-right" aria-hidden="true"></i>
                                    {% endif %}
                                </div>
                            </div>
                        {% else %}
                            <div class="item">
                                <img src="{{ asset(img.uploadDir ~ '/' ~ img.id ~ '.' ~ img.url) }}"
                                     alt="{{ img.alt }}"/>
                                <div class="carousel-caption">
                                    {% if img.description is not null %}
                                        <i class="fa fa-quote-left"
                                           aria-hidden="true"></i>&nbsp;&nbsp;{{ img.description }}&nbsp;&nbsp;<i
                                            class="fa fa-quote-right" aria-hidden="true"></i>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <!-- Carousel controls -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#myCarousel").carousel({
                interval: 6000,
                pause: false
            });
        });
    </script>
{% endblock %}

src/CMS/BlogBundle/Resources/views/Custom/Carousel/showTest.html.twig
{% extends('CMSBlogBundle::layout.html.twig') %}

{% block stylesheets %}{{ parent() }}
    <style>
        .carousel .item {
            max-height: 300px;
            min-height: 300px
        }

        .carousel img {
            position: absolute;
            top: 0;
            left: 0;
            min-width: 100%;
            height: 500px;
        }

        #myCarousel > div {
            background-color: black;
        }

    </style>
{% endblock %}

{% block cms_body %}

    <br>
    {% if carousel %}

        <div class="bs-example">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Carousel indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- Wrapper for carousel items -->
                <div class="carousel-inner">
                    {% for img in gallery %}
                        {% if loop.index == 1 %}
                            <div class="item active">
                                <img src="{{ asset(img.uploadDir ~ '/' ~ img.id ~ '.' ~ img.url) }}"
                                     alt="{{ img.alt }}"/>
                                <div class="carousel-caption">
                                    {% if img.description is not null %}
                                        <i class="fa fa-quote-left"
                                           aria-hidden="true"></i>&nbsp;&nbsp; {{ img.description }}&nbsp;&nbsp;<i
                                            class="fa fa-quote-right" aria-hidden="true"></i>
                                    {% endif %}
                                </div>
                            </div>
                        {% else %}
                            <div class="item">
                                <img src="{{ asset(img.uploadDir ~ '/' ~ img.id ~ '.' ~ img.url) }}"
                                     alt="{{ img.alt }}"/>
                                <div class="carousel-caption">
                                    {% if img.description is not null %}
                                        <i class="fa fa-quote-left"
                                           aria-hidden="true"></i>&nbsp;&nbsp;{{ img.description }}&nbsp;&nbsp;<i
                                            class="fa fa-quote-right" aria-hidden="true"></i>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <!-- Carousel controls -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block javascripts %}{{ parent() }}
    <script type="text/javascript">
        $(document).ready(function () {
            $("#myCarousel").carousel({
                interval: 6000,
                pause: false
            });
        });
    </script>
{% endblock %}